# Generated by Django 4.2.3 on 2023-07-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('legend', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
